# Generated by Django 2.1.2 on 2018-11-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181119_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_center',
            name='center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='labMat.Center'),
        ),
    ]
