# Generated by Django 2.1.2 on 2018-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labMat', '0002_unit_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_of_measure',
            name='measure',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
