# Generated by Django 2.1.2 on 2018-11-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labMat', '0003_auto_20181114_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group_name', models.CharField(max_length=100)),
            ],
        ),
    ]
