# Generated by Django 2.1.2 on 2018-11-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labMat', '0005_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labMat.Item_Group')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labMat.Unit_Of_Measure')),
            ],
        ),
    ]
