# Generated by Django 2.1.2 on 2018-11-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labMat', '0007_note_plan_user_item_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center_Item_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labMat.Center')),
                ('item_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labMat.Item_Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_item_group',
            name='item_group',
        ),
        migrations.RemoveField(
            model_name='user_item_group',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Item_Group',
        ),
    ]
