# Generated by Django 2.1.2 on 2018-11-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labMat', '0009_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
