# Generated by Django 2.1.2 on 2018-11-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labMat', '0010_auto_20181118_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_center',
            name='center',
        ),
        migrations.RemoveField(
            model_name='user_center',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Center',
        ),
    ]
