# Generated by Django 2.1.2 on 2018-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labMat', '0011_auto_20181119_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_group',
            name='slug',
            field=models.SlugField(default='slug', max_length=200),
        ),
    ]
